FROM python:3.13.7-slim
WORKDIR /usr/src/discord_bot

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY . .

RUN uv sync

EXPOSE 7860
ENV GRADIO_SERVER_NAME=0.0.0.0

RUN echo '#!/bin/sh\n\
uv run python -m discord_bot.init.log_loader\n\
uv run python -m discord_bot.init.db_loader\n\
uv run python -m discord_bot.app.main &\n\
exec uv run python -m discord_bot.adapters.view' > /entrypoint.sh && \
    chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
